services:
  - type: web
    name: sentinels-scanner
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/GauravBiraris/sentinels-scanner
    branch: main
    rootDir: .
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
